name: Publish MkDocs

on:
  push:
    branches:
      - main

# 🛠 ДОБАВЛЕНО: Явные права для робота на запись в репозиторий
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Подготовка папки docs для сборки
        run: |
          mkdir docs
          cp README.md docs/index.md
          cp -r book docs/
          cp -r core docs/
          cp -r rhizome docs/
          cp -r assets docs/
          
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Установка зависимостей
        run: pip install mkdocs-material pymdown-extensions
        
      - name: Сборка и публикация
        run: mkdocs gh-deploy --force
